services:
  postgres:
    container_name: 'udemy_clone'
    image: 'postgres:16-alpine'
    restart: 'always'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-scratch

volumes:
  postgres_data:

networks:
  nestjs-scratch:
